export enum MessageType {
  STANDARD = 'STANDARD',
  TOOL_EXECUTION = 'TOOL_EXECUTION',
  PLAN_SUMMARY = 'PLAN_SUMMARY',
  STEP_ANNOUNCEMENT = 'STEP_ANNOUNCEMENT',
  STEP_COMPLETE = 'STEP_COMPLETE',
}
